name: iproov_flutter_app
description: A Flutter app to demonstrate iProov onboarding
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  iproov_flutter: ^5.2.0
  http: ^0.13.5
  flutter_dotenv: ^5.1.0
  flutter_pdfview: ^1.2.7
  url_launcher: ^6.3.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  path_provider: ^2.0.11
  provider: ^6.1.1
  permission_handler: ^11.3.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icons/icon_app.png"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
